name: CheckPlayers
main: com.oneshotmc.checkplayers.CheckPlayers
version: 1
description: Look at your players
commands:
  checkplayers:
    description: Check the players on your server to see if they are doing anything bad.
    aliases: ["cp"]
    permission: checkplayers.use
    usage: "§cIncorrect syntax. Use /checkplayers [start / stop ]"
    permission-message: '§cYou do not have permission to use that command.'